---
title: "EPLC analysis"
author: "Jacob W. Roden-Foreman"
date: "`r Sys.time()`"
output:
  html_document:
    pandoc_args: "--dpi=150"
    fig_height: 3
    fig_width: 5
    code_folding: show
    df_print: kable
    toc: true
    toc_depth: 3
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup and import}
knitr::opts_chunk$set(echo = TRUE,
											results = "asis")

library(tidyverse)
library(tidylog)
library(data.table)
library(fst)
library(bit64)
library(DiagrammeR)
library(weights)



if(!file.exists("Data/final/final combined dataset with added vars and filters.fst")){
	mdata = read_fst("Data/final/final combined dataset.fst")
	mdata$hosp_ed = as.factor(mdata$hosp_ed)
}


med_iqi = function(x, w=mdata$discwt, na.rm=T, digits=2){
	
	digits = as.character(digits)
	
	fmt = paste0("%.", digits, "f [%.", digits, "f, %.", digits, "f]")
	
	if(is.null(w)){
		sprintf(fmt,
						quantile(x=x, probs = 0.5, na.rm = na.rm), 
						quantile(x=x, probs = 0.25, na.rm = na.rm), 
						quantile(x=x, probs = 0.75, na.rm = na.rm))
	} else{
		sprintf(fmt,
						spatstat::weighted.quantile(x=x, w=w, probs = 0.5, na.rm = na.rm), 
						spatstat::weighted.quantile(x=x, w=w, probs = 0.25, na.rm = na.rm), 
						spatstat::weighted.quantile(x=x, w=w, probs = 0.75, na.rm = na.rm))
	}
	
}



my.weighted.mean = function(x, w = mdata$discwt, na.rm=T){
	
	weighted.mean(x=x, w = w, na.rm = na.rm)
	
	
}


cat_perc = function(df, x, w = "discwt"){
	
	df = as.data.frame(df)
	x = df[, x]
	w = df[, w]
	rm(df)
	
	res = data.frame(var = unique(x))
	res$n = NA_real_
	res$perc = NA_real_
	total = sum(w, na.rm = T)
	
	for(i in 1:nrow(res)){
		res$n[i] = round( sum( w[x==res$var[i] ], na.rm = T ) )
	}
	
	res$var = as.character(res$var)
	res = res[!is.na(res$var), ]
	res = rbind(res, c("Missing", round(sum(w[ is.na(x) ])), NA))
	res$n = as.numeric(res$n)
	res$perc = round((res$n/total)*100, 2)
	
	
	res
	
}

cat_perc_by = function(df, groups, wt_var = "discwt"){
	
	plyr::count(df, groups, wt_var = wt_var) %>% 
	group_by_(groups[1]) %>% 
	mutate(perc = round((freq/sum(freq))*100, 2) ) %>% 
	ungroup() %>% 
	mutate(val = paste0(format(round(freq), big.mark = ","), " (", perc, "%)")) %>% 
	select(-freq, -perc) %>% 
	pivot_wider(names_from = groups[1], 
							values_from = val)
	
}




wilcox_weighted_p = function(y, x, w = mdata$discwt){
	y = data.table::frank(y)
	res = broom::tidy(lm(y ~ x, weights = w))
	res = res[2, "p.value"]
	res = as.numeric(res)
	
	if(res < 0.0001){
		res = "< 0.0001"
	} else{
		res = round(res, 4)
	}
	
	res
	
}





```





```{r add a few new vars}

if(!file.exists("Data/final/final combined dataset with added vars and filters.fst")){
	

#add definition for high risk vs. not -----
high_risk_codes = readxl::read_excel("high-risk_ecodes.xlsx",
																		 sheet = "ICD-9"
																		 )

#remove periods
high_risk_codes$ecode = str_remove_all(high_risk_codes$ecode, 
																			 fixed("."))


mdata$high_risk = mdata$ecode1 %in% high_risk_codes$ecode

mdata$high_risk[mdata$high_risk == TRUE] = "High-risk"
mdata$high_risk[mdata$high_risk == "FALSE"] = "Non-high-risk"

rm(high_risk_codes)




#pull out trauma center level -----
#NEDS Stratum: 2nd digit – Trauma: 
#(0) Not a trauma center,
#(1) Trauma center level I, 
#(2) Trauma center level II,
#(3) Trauma center level III.
#Collapsed categories used for strata with small sample sizes: 
#(4) Nontrauma center or trauma center level III, 
#(8) Trauma center level I or II. 


mdata$hosp_trauma_level = case_when(
	substring(mdata$neds_stratum, 2, 2) == 1 ~ "Trauma center level I",
	substring(mdata$neds_stratum, 2, 2) == 2 ~ "Trauma center level II",
	substring(mdata$neds_stratum, 2, 2) == 3 ~ "Trauma center level III",
	TRUE ~ "All Other Hospitals") %>% 
	factor(., 
				 levels = c("Trauma center level I", 
				 					 "Trauma center level II",
				 					 "Trauma center level III",
				 					 "All Other Hospitals"),
				 ordered = TRUE)







#add injury dx flags ----

dx = read_fst("Data/final/dx_final.fst",
							columns = c("key_ed", "dx1"))
source("icd9_to_Barell.R")

bar = icd9_to_barrel(dx$dx1)

all.equal(as.integer64(mdata$key_ed), as.integer64(dx$key_ed))


# Brain Injury: 850-854
mdata$injury_brain = dx$dx1 %in% as.character(85000:85499)

# Skull Fracture: 800-804
mdata$injury_skull_fx = dx$dx1 %in% as.character(80000:80499)

# Cervical Spine Fracture
mdata$injury_cspine = bar$region_3 %in% c("CERVICAL VCI", "CERVICAL SCI")

# Rib or Sternum Fracture: 809
mdata$injury_rib_fx = dx$dx1 %in% as.character(80900:80999)

# Cardiac or Pulmonary Injury: 860-861
mdata$injury_cardio_pulm = dx$dx1 %in% as.character(86000:86199)

# Thoracic Spine Fracture
mdata$injury_tspine = bar$region_3 %in% c("THORACIC/DORSAL VCI", "THORACIC/DORSAL SCI")

# Lumbar Spine Fracture
mdata$injury_lspine = bar$region_3 %in% c("THORACIC/DORSAL VCI", "THORACIC/DORSAL SCI")


# Solid Abdominal Organ Injury
mdata$injury_solid_abd = dx$dx1 %in% as.character(c( 86400:86699, #liver, spleen, kidneys
																										 86381:86384, #pancreas
																										 86391:86394  #pancreas
																										 ))

# Hollow Viscera Injury
mdata$injury_hollow_abd = dx$dx1 %in% as.character(c( 86300:86380, #stomach, intestines
																											86389, 86390, 86399, #other GI
																											86700:86799 #bladder, ureter, urethra
																										 ))




# Upper Extremity Fracture
mdata$injury_ue_fx = bar$dx_type %in% "FRACTURES" & bar$region_2 %in% "UPPER EXTREMITY"

# Pelvis Fracture: 808
mdata$injury_pelvic_fx = dx$dx1 %in% as.character(80800:80899)

# Lower Extremity Fracture
mdata$injury_le_fx = bar$dx_type %in% "FRACTURES" & bar$region_2 %in% "LOWER EXTREMITY"

rm(bar, dx)




# a little recoding
mdata$year_whole = mdata$year %>% substr(., 1, 4) %>% as.integer()

mdata$pay1_recode = case_when(
	mdata$pay1 == "Medicare" | mdata$pay1 == "Medicaid" ~ "Medicare/Medicaid",
	TRUE ~ as.character(mdata$pay1)
) %>% as.factor()



write_fst(mdata, "Data/final/final combined dataset with added vars and filters.fst")


} else{
	mdata = read_fst("Data/final/final combined dataset with added vars and filters.fst")
	mdata$hosp_ed = as.factor(mdata$hosp_ed)
}


```



\
\
\
\

# CONSORT Flow Chart
```{r}

mdata = filter(mdata, !is.na(mortality))
mdata = filter(mdata, !is.na(totchg))
n = nrow(mdata)



pt_counts = read_lines("nobs log.txt") %>%
	str_split_fixed(., " = ",  n=2) %>% 
	as.data.frame()

#update case count log if not already updated
if(!any(str_detect(pt_counts$V1, "N_obs removing missing mortality, total charges"))){
	cat("N_obs removing missing mortality, total charges = ", 
			format(n, big.mark=","), "\n", file="nobs log.txt", append=T)
}



pt_counts = read_lines("nobs log.txt") %>%
	str_split_fixed(., " = ",  n=2) %>% 
	as.data.frame()

pt_counts$V2 = trimws(pt_counts$V2)

pt_counts = pt_counts[pt_counts$V1 != "N_obs after all filters", ]


pt_counts$n = str_remove_all(pt_counts$V2, ",") %>% as.numeric()
pt_counts$n_change = lag(pt_counts$n, 1) - pt_counts$n
pt_counts$n_change = prettyNum(pt_counts$n_change, big.mark = ",")



pt_counts = rbind(pt_counts, 
									c("N_obs after all filters", format(nrow(mdata), big.mark = ","),  nrow(mdata), NA ))


pt_counts$label = c("Number of encounters in NEDS dataset, 2010-2016",
										"Principal diagnosis of trauma",
										"Age \u2265 50 years",
										"Principal external cause of injury not one of burns,\nbites/stings, overexertion, poisoning, or\nmisadventures of medical/surgical care",
										"Not missing data for mortality or total charges",
										"Included for analysis"
)





DiagrammeR::grViz("
digraph graph2 {

graph [layout = dot, rankdir = TB]

# node definitions with substituted label text
node [shape = rectangle, width = 4, fillcolor = Biege]
a [label = '@@1']
b [label = '@@2']
c [label = '@@3']
d [label = '@@4']
e [label = '@@5']
f [label = '@@6']

b_out [label = '@@7']
c_out [label = '@@8']
d_out [label = '@@9']
e_out [label = '@@10']


a -> b -> c -> d -> e -> f
a -> b_out -> c_out -> d_out -> e_out

}

[1]: paste0(pt_counts$label[1], ': n = ', pt_counts$V2[1])
[2]: paste0(pt_counts$label[2], ': n = ', pt_counts$V2[2])
[3]: paste0(pt_counts$label[3], ': n = ', pt_counts$V2[3])
[4]: paste0(pt_counts$label[4], ': n = ', pt_counts$V2[4])
[5]: paste0(pt_counts$label[5], ': n = ', pt_counts$V2[5])
[6]: paste0(pt_counts$label[6], ': n = ', pt_counts$V2[6])
[7]: paste0('Excluded: n = ', pt_counts$n_change[2])
[8]: paste0('Excluded: n = ', pt_counts$n_change[3])
[9]: paste0('Excluded: n = ', pt_counts$n_change[4])
[10]: paste0('Excluded: n = ', pt_counts$n_change[5])
"
)





```



\
\
\



# Table 1. Characteristics of `r format(nrow(mdata), big.mark=",")` encounters with traumatic injury


```{r}



count(mdata, high_risk) %>% 
    mutate(pct = round((n/sum(n))*100,2),
    			 n = format(n, big.mark = ",")
    			 )


count(mdata, high_risk, wt = discwt) %>% 
    mutate(pct = round((n/sum(n))*100,2),
    			 n = format(n, big.mark = ",")
    			 )




mdata %>%
	group_by(high_risk) %>% 
	summarise(
						age = med_iqi(age, w = discwt),
						elixhauser = med_iqi(elixhauser, w = discwt),
						pDeath = med_iqi(pDeath*100, w = discwt)#,
						# los_ip = med_iqi(los_ip, w = discwt),
						# totchg_ed = med_iqi(totchg_ed, w = discwt),
						# totchg_ip = med_iqi(totchg_ip, w = discwt),
						# totchg = med_iqi(totchg, w = discwt)
	) %>% t() %>% as.data.frame() %>% 
	knitr::kable()


wilcox_weighted_p(mdata$age, mdata$high_risk)
wilcox_weighted_p(mdata$elixhauser, mdata$high_risk)
wilcox_weighted_p(mdata$pDeath, mdata$high_risk)
wilcox_weighted_p(mdata$los_ip, mdata$high_risk)
wilcox_weighted_p(mdata$totchg_ed, mdata$high_risk)
wilcox_weighted_p(mdata$totchg_ip, mdata$high_risk)
wilcox_weighted_p(mdata$totchg, mdata$high_risk)



cat_perc_by(mdata, c("high_risk", "female"))
weights::wtd.chi.sq(mdata$high_risk, mdata$female, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()


cat_perc_by(mdata, c("high_risk", "injury_brain"))
weights::wtd.chi.sq(mdata$high_risk, mdata$injury_brain, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()



cat_perc_by(mdata, c("high_risk", "injury_skull_fx"))
weights::wtd.chi.sq(mdata$high_risk, mdata$injury_skull_fx, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()

cat_perc_by(mdata, c("high_risk", "injury_cspine"))
weights::wtd.chi.sq(mdata$high_risk, mdata$injury_cspine, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()

cat_perc_by(mdata, c("high_risk", "injury_rib_fx"))
weights::wtd.chi.sq(mdata$high_risk, mdata$injury_rib_fx, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()

cat_perc_by(mdata, c("high_risk", "injury_cardio_pulm"))
weights::wtd.chi.sq(mdata$high_risk, mdata$injury_cardio_pulm, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()

cat_perc_by(mdata, c("high_risk", "injury_tspine"))
weights::wtd.chi.sq(mdata$high_risk, mdata$injury_tspine, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()

cat_perc_by(mdata, c("high_risk", "injury_lspine"))
weights::wtd.chi.sq(mdata$high_risk, mdata$injury_lspine, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()

cat_perc_by(mdata, c("high_risk", "injury_solid_abd"))
weights::wtd.chi.sq(mdata$high_risk, mdata$injury_solid_abd, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()

cat_perc_by(mdata, c("high_risk", "injury_hollow_abd"))
weights::wtd.chi.sq(mdata$high_risk, mdata$injury_hollow_abd, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()

cat_perc_by(mdata, c("high_risk", "injury_ue_fx"))
weights::wtd.chi.sq(mdata$high_risk, mdata$injury_ue_fx, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()

cat_perc_by(mdata, c("high_risk", "injury_pelvic_fx"))
weights::wtd.chi.sq(mdata$high_risk, mdata$injury_pelvic_fx, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()

cat_perc_by(mdata, c("high_risk", "injury_le_fx"))
weights::wtd.chi.sq(mdata$high_risk, mdata$injury_le_fx, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()

cat_perc_by(mdata, c("high_risk", "pay1_recode"))
weights::wtd.chi.sq(mdata$high_risk, mdata$pay1_recode, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()

cat_perc_by(mdata, c("high_risk", "zipinc_qrtl"))
weights::wtd.chi.sq(mdata$high_risk, mdata$zipinc_qrtl, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()

cat_perc_by(mdata, c("high_risk", "died_visit"))
weights::wtd.chi.sq(mdata$high_risk, mdata$died_visit, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()

cat_perc_by(mdata, c("high_risk", "disp_ed"))
weights::wtd.chi.sq(mdata$high_risk, mdata$disp_ed, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()

cat_perc_by(mdata, c("high_risk", "edevent"))
weights::wtd.chi.sq(mdata$high_risk, mdata$edevent, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()

cat_perc_by(mdata, c("high_risk", "disp_ip"))
weights::wtd.chi.sq(mdata$high_risk, mdata$disp_ip, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()

cat_perc_by(mdata, c("high_risk", "hosp_trauma_level"))
weights::wtd.chi.sq(mdata$high_risk, mdata$hosp_trauma_level, 
										weight = mdata$discwt, mean1 = F) %>% knitr::kable()





```


\
\
\
\



# Table 2. High-risk mechanisms of injury by TMPM probability of death, actual mortality, and median total charge  

```{r}

```


\
\
\
\

# Table 3. Characteristics of `r format(nrow(mdata), big.mark=",")` encounters with traumatic injuries from high-risk activities by survival status  

```{r}

```





\
\
\
\



 
https://m-clark.github.io/posts/2019-10-20-big-mixed-models/#additive-models-as-mixed-models

 
```{r mixed model}
library(mgcv)
library(gammit)

```



\
\
\
\





```{r} 
pander::pander(sessionInfo())
```
